# Generated by Django 4.2.2 on 2023-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="additional_image",
            field=models.ImageField(blank=True, null=True, upload_to="movies/"),
        ),
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default=1, upload_to="gallary"),
            preserve_default=False,
        ),
    ]
