# Generated by Django 4.1 on 2023-08-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0002_movie_additional_image_movie_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_image",
                    models.ImageField(blank=True, null=True, upload_to="movies/"),
                ),
            ],
        ),
    ]
